name: PR

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  scan-sast:
    name: Scan SAST
    uses: Avodah-Inc/github-actions/.github/workflows/pr-scan-sast.yml@7a11234f8530d810e1ad04b67cd809dca6e316ae # 4.12.0
    permissions:
      actions: read
      checks: write
      contents: read
    secrets:
      GH_TOKEN: ${{ secrets.OPENTOFU_GH_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  scan-sca:
    name: Scan SCA
    uses: Avodah-Inc/github-actions/.github/workflows/pr-scan-sca.yml@7a11234f8530d810e1ad04b67cd809dca6e316ae # 4.12.0
    permissions:
      checks: write
      contents: read

  scan-secrets:
    name: Scan Secrets
    uses: Avodah-Inc/github-actions/.github/workflows/scan-secrets.yml@7a11234f8530d810e1ad04b67cd809dca6e316ae # 4.12.0
    permissions:
      checks: write
      contents: read
